### ISSUE TITLE
Health bar is useless

### ISSUE THREAD

**Issue by Flu** [DanielDeSouzaMelo/ant#1]
So ants have full health by default. The health bar does not show up then. If you put the magnifying glass on it, their health will start to decrease. and the bar shows up to tell you how much until they catch fire. If you take the lens of it, they will start to regenerate

**Comment by DanielDeSouzaMelo** [comment]
Ill change it

**Comment by Flu** [comment]
I don't believe you. Do you have what it takes to change it? Prove me wrong and do it

**Comment by DanielDeSouzaMelo** [comment]
here i changed it dipshit
